rules:
  # Evitar contraseñas hardcodeadas
  - id: avoid-hardcoded-passwords
    patterns:
      - pattern: $VAR = "$SECRET"
      - pattern-not: $VAR = ""
    message: "Evita hardcodear contraseñas o secretos en el código."
    languages: [dart]
    severity: ERROR

  # Manejo adecuado de excepciones
  - id: avoid-empty-catch-blocks
    pattern: |
      try {
        ...
      } catch (e) {
      }
    message: "Evita bloques catch vacíos. Maneja las excepciones adecuadamente."
    languages: [dart]
    severity: WARNING

  # Uso adecuado de async/await
  - id: async-await-check
    pattern: |
      await $ASYNC_FUNCTION(...)
    message: "Asegúrate de manejar las operaciones asíncronas correctamente con 'try/catch'."
    languages: [dart]
    severity: INFO

  # Evitar el uso de print en producción
  - id: avoid-print-debug
    pattern: print($MSG)
    message: "Evita usar 'print' en producción. Usa logs o herramientas de depuración."
    languages: [dart]
    severity: WARNING

  # Evitar variables no utilizadas
  - id: avoid-unused-variables
    pattern: var $VAR = $VALUE;
    message: "Elimina las variables no utilizadas para mantener el código limpio."
    languages: [dart]
    severity: WARNING
