rules:
  - id: avoid-hardcoded-passwords
    patterns:
      - pattern: password = "$SECRET"
      - pattern-not: password = ""
    message: "Evita hardcodear contraseñas o secretos en el código."
    languages: [dart]
    severity: ERROR

  - id: avoid-todo-comments
    pattern: // TODO
    message: "Los TODO deben resolverse antes del release."
    languages: [dart]
    severity: WARNING

  - id: avoid-print-debug
    pattern: print($MSG)
    message: "Evita usar 'print' en producción. Usa logs o herramientas de depuración."
    languages: [dart]
    severity: WARNING

  - id: missing-null-check
    pattern: if ($VAR != null) {
    message: "Asegúrate de manejar correctamente los nulls, o usa el operador '?.'."
    languages: [dart]
    severity: INFO

  - id: use-const-when-possible
    pattern: Widget($ARGS)
    message: "Considera usar 'const' para mejorar el rendimiento si los valores son constantes."
    languages: [dart]
    severity: INFO
