name: Build

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Mejora la relevancia del análisis

      - name: Setup Flutter (3.29.3)
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          version: '3.29.3'

      - name: Install dependencies
        run: flutter pub get

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
