name: Build

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Flutter (3.29.3)
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          version: '3.29.3'

      - name: Install dependencies
        run: |
          cd proyecto
          flutter pub get

      - name: Install SonarScanner
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner-cli-5.0.1.3006-linux.zip
          echo "$(pwd)/sonar-scanner-5.0.1.3006-linux/bin" >> $GITHUB_PATH  # Método correcto para PATH

      - name: Run SonarScanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd proyecto
          sonar-scanner -Dsonar.login=$SONAR_TOKEN
