name: SonarCloud Analysis

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [opened, synchronized, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'

      - name: Install dependencies
        run: |
          cd proyecto
          flutter pub get

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ./proyecto
          # Opcional: Forzar análisis si el proyecto ya existe
          args: >
            -Dsonar.projectKey=erickorganizacion_proyecto
            -Dsonar.organization=erickorganizacion
            -Dsonar.host.url=https://sonarcloud.io
