name: SonarCloud Sync

on:
  push:
    branches: [main, master]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  sonarcloud-scan:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: stable

      - name: Install dependencies
        run: |
          cd proyecto
          flutter pub get

      - name: Install SonarScanner (Windows)
        run: |
          # Descarga directa a la misma ruta que usas localmente
          Invoke-WebRequest -Uri "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-windows.zip" -OutFile "C:\sonar-scanner.zip"
          Expand-Archive -Path "C:\sonar-scanner.zip" -DestinationPath "C:\" -Force

      - name: Run SonarScanner (IDÉNTICO a tu comando local)
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Debe coincidir con tu token local
        run: |
          cd proyecto
          $env:SONAR_TOKEN="${{ secrets.SONAR_TOKEN1 }}"
          C:\sonar-scanner\bin\sonar-scanner.bat  # ¡Misma ruta exacta!
