name: Flutter Dependency Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Install dependencies
        working-directory: proyecto
        run: flutter pub get

      # Instalación correcta de Snyk CLI (método alternativo)
      - name: Install Snyk CLI
        run: |
          npm install -g snyk
          snyk --version
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Escaneo y generación de SARIF
      - name: Run Snyk scan
        working-directory: proyecto
        run: |
          snyk test --file=pubspec.yaml --package-manager=pub --sarif --json > snyk_report.sarif || echo "Snyk scan completed with findings"
          
      # Subir resultados (si el archivo existe)
      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()  # Se ejecuta siempre que exista el archivo
        with:
          sarif_file: proyecto/snyk_report.sarif
