name: Flutter Dependency Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Install dependencies
        working-directory: proyecto
        run: flutter pub get

      # Proper Snyk installation
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Snyk CLI
        run: |
          npm install -g snyk
          snyk --version

      # Secure scan with proper SARIF output
      - name: Run Snyk scan
        working-directory: proyecto
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          # Create Snyk directory at the root of the repository if it doesn't exist
          mkdir -p Snyk
          snyk test --file=pubspec.yaml --package-manager=pub --sarif > Snyk/snyk_report.sarif || true
          # Validate SARIF format
          jq empty Snyk/snyk_report.sarif && echo "SARIF is valid" || echo "SARIF validation failed"

      # Updated CodeQL upload action
      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: Snyk/snyk_report.sarif
