name: Flutter Dependency Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Install dependencies
        working-directory: proyecto-si889-2025-i-u1-tapia_poma_ayma/proyecto
        run: flutter pub get

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Create Snyk directory
        run: mkdir -p proyecto-si889-2025-i-u1-tapia_poma_ayma/Snyk

      - name: Run Snyk scan
        working-directory: proyecto-si889-2025-i-u1-tapia_poma_ayma/proyecto
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk test --file=pubspec.yaml --package-manager=pub --sarif > ../Snyk/snyk_report.sarif || echo "Scan completed with findings"

      - name: Verify SARIF file
        run: |
          echo "Contenido del directorio Snyk:"
          ls -la proyecto-si889-2025-i-u1-tapia_poma_ayma/Snyk/
          echo "Validación del archivo SARIF:"
          jq empty proyecto-si889-2025-i-u1-tapia_poma_ayma/Snyk/snyk_report.sarif && echo "SARIF válido" || echo "Error en SARIF"

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: proyecto-si889-2025-i-u1-tapia_poma_ayma/Snyk/snyk_report.sarif
