name: Semgrep Scan and Publish to gh-pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write  # Permiso para hacer push a otra rama

jobs:
  semgrep:
    name: Run Semgrep and Publish Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necesario para cambiar de rama después

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep and output JSON
        run: |
          cd proyecto
          semgrep --config=auto --json > semgrep_report.json

      - name: Switch to gh-pages branch
        run: |
          git fetch origin gh-pages || git checkout --orphan gh-pages
          git checkout gh-pages

      - name: Copy Semgrep Report to semgrep/ folder
        run: |
          mkdir -p semgrep
          cp proyecto/semgrep_report.json semgrep/semgrep_report.json

      - name: Commit and Push Semgrep report to gh-pages
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add semgrep/semgrep_report.json
          git commit -m "Update Semgrep report 🚀" || echo "No changes to commit"
          git push origin gh-pages
