name: Flutter Dependency Audit (JSON)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Install dependencies
        working-directory: proyecto
        run: flutter pub get

      - name: Generate JSON report
        run: |
          mkdir -p DartPubOutdated
          cd proyecto
          dart pub outdated --mode=null-safety --json > ../DartPubOutdated/outdated.json

      - name: Upload JSON report
        uses: actions/upload-artifact@v4  # ¡Versión actualizada!
        with:
          name: DartPubOutdated-JSON
          path: DartPubOutdated/outdated.json
