name: Flutter Audit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Install Flutter dependencies
        working-directory: proyecto
        run: flutter pub get

      - name: Run dart pub audit
        working-directory: proyecto
        run: dart pub audit
