name: Flutter Security Audit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security-audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      # Si pubspec.yaml está en /proyecto/
      - name: Install dependencies
        working-directory: proyecto  # Solo si está dentro de una carpeta "proyecto"
        run: flutter pub get

      # Escaneo con Snyk (opcional)
      - name: Run Snyk security scan
        working-directory: proyecto  # Mismo directorio que arriba
        run: snyk test --file=pubspec.yaml --package-manager=pub --fail-on=all

      # Alternativa sin Snyk
      - name: Check outdated packages
        working-directory: proyecto
        run: dart pub outdated --mode=null-safety
