name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze:
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.3"  # Actualiza a una versión compatible con Dart SDK ^3.7.0

      - name: Install dependencies
        run: |
          cd proyecto  # Cambiar al directorio donde está el proyecto
          flutter pub get

      - name: Run SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd proyecto  # Asegúrate de estar en la carpeta correcta
          flutter pub global activate sonar_flutter
          flutter pub global run sonar_flutter
