name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud_analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.3'

    - name: Install dependencies
      run: |
        cd proyecto
        flutter pub get

    - name: Run tests (if available)
      run: |
        cd proyecto
        if [ -d "test" ] && [ "$(find test -name '*_test.dart' | wc -l)" -gt 0 ]; then
          flutter test
        else
          echo "No test files found, skipping tests..."
        fi

    - name: Run SonarCloud analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        cd proyecto
        sonar-scanner \
          -Dsonar.projectKey=erickorganizacion_proyecto \
          -Dsonar.organization=erickorganizacion \
          -Dsonar.projectName="Flutter App" \
          -Dsonar.projectVersion=1.0 \
          -Dsonar.sources=lib \
          -Dsonar.tests=test \
          -Dsonar.exclusions="**/*.g.dart,**/*.freezed.dart,**/*.mocks.dart" \
          -Dsonar.inclusions="**/*.dart" \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=$SONAR_TOKEN
