name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar_analysis:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.3'

    - name: Install dependencies
      run: |
        cd proyecto  # Cambiar al directorio correcto
        flutter pub get

    - name: Skip tests if none exist
      run: |
        if [ -d "test" ] && [ "$(find test -name '*_test.dart' | wc -l)" -gt 0 ]; then
          flutter test
        else
          echo "No test files found, skipping tests..."
        fi

    - name: Run SonarQube analysis with Docker
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        docker run --rm \
          -v $GITHUB_WORKSPACE:/usr/src \
          -e SONARQUBE_SCANNER_PARAMS="-Dsonar.projectKey=erickorganizacion_proyecto -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN -Dsonar.sources=lib -Dsonar.tests=test -Dsonar.inclusions='**/*.dart' -Dsonar.projectBaseDir=/usr/src" \
          sonarsource/sonar-scanner-cli:latest
