name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar_analysis:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.3'

    - name: Install dependencies
      run: |
        cd proyecto  # Cambiar al directorio correcto
        flutter pub get

    - name: Skip tests if none exist
      run: |
        cd proyecto
        mkdir -p test  # Asegura que la carpeta test exista
        if [ "$(find test -name '*_test.dart' | wc -l)" -gt 0 ]; then
          flutter test
        else
          echo "No test files found, skipping tests..."
        fi || true  # Evita que falle el workflow si no hay tests

    - name: Run SonarCloud analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        cd proyecto
        docker run \
          --rm \
          -e SONAR_HOST_URL=https://sonarcloud.io \
          -e SONAR_LOGIN=$SONAR_TOKEN \
          -v $(pwd):/usr/src \
          sonarsource/sonar-scanner-cli \
          -Dsonar.projectKey=erickorganizacion_proyecto \
          -Dsonar.organization=YOUR_ORG_KEY \
          -Dsonar.sources=./lib \
          -Dsonar.tests=./test \
          -Dsonar.inclusions="**/*.dart"
