name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar_analysis:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.3'

    - name: Install dependencies
      run: |
        cd proyecto  # Cambiar al directorio correcto
        flutter pub get

    - name: Skip tests if none exist
      run: |
        if [ -d "test" ] && [ "$(find test -name '*_test.dart' | wc -l)" -gt 0 ]; then
          flutter test
        else
          echo "No test files found, skipping tests..."
        fi

    - name: Install SonarQube scanner
      run: |
        cd proyecto  # Cambiar al directorio correcto
        curl -sSLo sonarscanner.zip https://binaries.sonarsource.com/DownloadScanner/sonar-scanner-cli-4.7.0.2747-linux.zip
        unzip sonarscanner.zip
        export PATH=$PWD/sonar-scanner-4.7.0.2747-linux/bin:$PATH

    - name: Run SonarQube analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        cd proyecto  # Cambiar al directorio correcto
        sonar-scanner \
          -Dsonar.projectKey=erickorganizacion_proyecto \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=$SONAR_TOKEN \
          -Dsonar.sources=lib \
          -Dsonar.tests=test \
          -Dsonar.inclusions="**/*.dart" \
          -Dsonar.projectBaseDir=$PWD
