name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar_analysis:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.3'

    - name: Install dependencies
      run: |
        cd proyecto  # Cambiar al directorio correcto
        flutter pub get

    - name: Run tests
      run: |
        cd proyecto  # Cambiar al directorio correcto
        flutter test

    - name: Install SonarQube scanner
      run: |
        cd proyecto  # Cambiar al directorio correcto
        curl -sSLo sonarscanner.zip https://binaries.sonarsource.com/DownloadScanner/sonar-scanner-cli-4.7.0.2747-linux.zip
        unzip sonarscanner.zip
        export PATH=$PWD/sonar-scanner-4.7.0.2747-linux/bin:$PATH

    - name: Run SonarQube analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        cd proyecto  # Cambiar al directorio correcto
        sonar-scanner \
          -Dsonar.projectKey=erickorganizacion_proyecto \
          -Dsonar.host.url=http://localhost:9000 \
          -Dsonar.login=$SONAR_TOKEN
