name: Flutter CI with SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Flutter
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.3'

    # Install dependencies
    - name: Install dependencies
      run: flutter pub get

    # Run tests
    - name: Run tests
      run: flutter test

    # Run SonarQube analysis
    - name: SonarQube analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Agrega tu token de SonarQube
      run: |
        curl -sSLo sonarscanner.zip https://binaries.sonarsource.com/DownloadScanner/sonar-scanner-cli-4.7.0.2747-linux.zip
        unzip sonarscanner.zip
        export PATH=$PWD/sonar-scanner-4.7.0.2747-linux/bin:$PATH
        sonar-scanner \
          -Dsonar.projectKey=your_project_key \
          -Dsonar.host.url=http://your-sonarqube-server.com \
          -Dsonar.login=$SONAR_TOKEN
