name: Build

on:
  push:
    branches:
      - main  # Cambiado a 'main' en lugar de 'master'
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]  # Cambiado a 'main' también

jobs:
  flutter_build:
    name: Flutter Build and SonarQube Scan
    runs-on: ubuntu-latest

    steps:
      # Paso para obtener el código del repositorio
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Desactiva el clon superficial para un análisis más preciso

      # Instala Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'  # Especifica la versión de Flutter que usas

      # Instala las dependencias de Flutter
      - name: Install dependencies
        run: flutter pub get

      # Realiza el análisis de SonarQube desde la carpeta 'proyecto'
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          working-directory: proyecto  # Cambia al directorio donde está el archivo sonar-project.properties
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
